app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)
from . import views

app/home/views.py
from flask import render_template, abort, request,flash
from flask_login import login_required, current_user
from sqlalchemy import and_
from . import home
from ..models import UserBook, Book
from .. import db
from datetime import datetime,timedelta





@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
	if not current_user.is_admin:
		abort(403)
	return render_template('home/admin_dashboard.html', title="Admin Dashboard")


@home.route('/')
def homepage():
	'''
		Homepage for home
	'''
	return render_template('home/index.html', title="Homepage")

@home.route('/dashboard')
def dashboard():
	'''
		Homepage for home
	'''
	return render_template('home/dashboard.html', title="Dashboard")
@home.route('/allbooks')
def books():
	return render_template('home/allbooks.html', title="All Books")

@home.route('/borrow_book', methods=['POST'])
def borrow_books():
	# Save borrowed book
	user_id = current_user.id
	books = get_user_borrowed_books(user_id)

	borrow_date = timestamp = datetime.now()
	return_date = borrow_date + timedelta(10)
	book_id = request.form['book_id']

	if book_id:
		add_user_book = True

		books = get_user_borrowed_books(user_id)
		no_of_books = books.count()
		return_date = return_date.strftime("%d-%m-%y")
		borrow_date = borrow_date.strftime("%d-%m-%y")

		user_book = UserBook(user_id = user_id, book_id = book_id)
		try:
			if book_is_borrowed(user_id, book_id):
				#check if owner has book already
				flash("You have already Borrowed this Book, Please return it first :)")
			else:		
				#go ahead and allow user to borrow book
				db.session.add(user_book)
				db.session.commit()
				flash("Successfully Borrowed book, wait for approval from admin",'success')

		except:
			flash("You have borrowed this book already!")
		

	return render_template('home/borrowed_books.html', get_dates = get_dates, books = books, title="Borrow Books")

@home.route('/borrowed_books', methods = ['GET', 'POST'])
@login_required
def list_borrowed_books():
	user_id = current_user.id

	books = UserBook.query.get(user_id)
	if not books:
		books = None

	return render_template('home/borrowed_books.html',  books = books, title="Borrowed Books")
	


def book_is_borrowed(user_id, book_id):
	return UserBook.query.filter(UserBook.user_id==user_id).filter(UserBook.book_id==book_id).first()

def get_user_borrowed_books(user_id):
	# return UserBook.query.join(Book, UserBook.books_id==books.id).filter(UserBook.user_id==request.form['user_id'])
	return Book.query.join(UserBook, Book.id==UserBook.book_id).filter(UserBook.user_id==user_id)

def get_dates(user_id, book_id):
	dates = UserBook.query.filter(user_id == user_id, book_id == book_id).first()
	# raise
	return dates

	

	

app/templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h3 align="center">Admin Dashboard - For administrators only</h3   >
                    <hr class="intro-divider">
                    </ul>
                </div>
                <div class="card text-center">
                  <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                    <li class="pull-right" style="margin-right: 10%;"> <a href="{{ url_for('admin.add_book') }}" class="btn btn-default btn-lg">Add Book <i class="fa fa-plus"></i></a></li>
                      <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('admin.borrowed_books')}}">Borrowed Books</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="/admin/books">All Books</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link disabled" href="#">Admin</a>
                      </li>
                    </ul>
                  </div>
                  <div class="card-block">
                       <br>
                  <br>
                  <br>
                  <br>
                  <br>
                    <!-- <h2 class="card-title">Change Stuff about the Library here!</h2>
                    <p class="card-text">Access the quick links below to start administration.</p> -->
      
                  </div>
                  <br>
                  <br>
                  <br>
                  <br>
                  <br>
                  <hr style="margin-bottom: 20px;">

                <div class="col-md-12">
                    <div class="col-md-3">
                     <a href="{{ url_for('admin.list_books') }}" class="btn btn-primary dash-btn">All Books<br><i style="font-size: 240%;" class="glyphicon glyphicon-list"></i></a>
                    </div>
                      <div class="col-md-3">
                     <a href="{{url_for('admin.borrowed_books')}}" class="btn btn-success dash-btn">Borrowed Books<br><i style="font-size: 240%;" class="glyphicon glyphicon-transfer"></i></a>
                    </div>
                      <div class="col-md-3">
                     <a href="#" class="btn btn-primary dash-btn">Returned Books<br><i style="font-size: 240%;" class="glyphicon glyphicon-level-up"></i></a>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/allbooks.html
{% extends "base.html" %}
{% block title %}All Books{% endblock %}
{% block body%}
<hr>

<div class="card-deck container">
  <div class="card col-md-3 card-f">
    <div class="card-block">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

{% endblock%}

app/templates/home/borrowed_books.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Bookss{% endblock %}
{% block body %}
  
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Books you currently have</h1>
                <div class=" container">
          {% if current_user.is_authenticated %}
                  {% if current_user.is_admin %}
                      <button class="btn btn-default"><a href="{{ url_for('home.admin_dashboard') }}">Admin Dashboard</a></button>
                    {% else %}

                 <button class="btn btn-default"><a href="{{ url_for('home.dashboard') }}"><< Return to Dashboard</a></li></button>
                 <button class="btn btn-default"><a href="{{ url_for('admin.list_books') }}"><< Browse Books</a></li></button>
                  {% endif %}
          {% endif %}
        </div>
        {% if books %}
          <div class="container">
              {% for book in books %}
                  <div class="card-deck col-md-4" style="padding: 10px;">
                    <div class="card card-f">
                      <div class="card-block">
                        <h4 class="card-title"><i class="glyphicon glyphicon-book"></i>  {{ book.title }}</h4>
                        <p class="card-text" style="min-height: 60px;">{{ book.description }}</p>
                              <hr>
                       <div class="col-12" style="display: inline-block;">
                        <small class="text-muted col-xs-6 no-padding"><i class="glyphicon glyphicon-time" style="color:green;"></i> Date Borrowed: {{get_dates(current_user.id, book.id).borrow_date}}<hr></small>

                        <small class="text-muted col-xs-6  no-padding"><i class="glyphicon glyphicon-time" style="color: red;"></i> Date Due: {{get_dates(current_user.id, book.id).return_date}}</small>
                        </div>
                      </div>
                  {% if current_user.id == book.user_id %}
                        <button class="btn btn-xs btn-info">
                                   <a href="{{ url_for('home.borrow_books', id=book.id, user_id = current_user.id) }}" style="color: white;">
                                    <i class="fa fa-thumbs"></i> Return Book
                                   </a>
                        </button>
                    {% endif %}
                    </div>
                  </div>
                  <!-- check if user is admin -->
              {% endfor %}
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3 class="lead"><i class="glyphicon` glyphicon-space-shuttle"></i> You have not borrowed any books. </h3>
            <hr class="intro-divider">
        {% endif %}
      
        </div>
        </div>
        </div>
{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}


<div class="container margin-top-50">
</div>
{% if current_user %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h3> Welcome, Dashboard</h2>
                          <ul class="nav nav-pills  ">
                              <li><a class="btn btn-default" href="{{ url_for('admin.list_books') }}">Browse Books</a></li>
                              <li><a  class="btn btn-default" href="{{ url_for('home.list_borrowed_books') }}">Borrowed Books</a></li>
                                <ul class="nav nav-pills  pull-right">
                                <li role="presentation"><a href="#">Account Settings</a></li>
                            </ul>
                            </ul>
                          
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
        <div style="position: relative;" class="container">
            <img src="{{ url_for('static', filename='img/books.jpg') }}" width="100%" style="position:absolute; left:0px; top:0px;  ">

           <h2 align="center"> Welcome to Super lib! :-)</h2>
            <div align="center" class="card card-inverse card-danger col-md-12 " style="width: 100%;padding: 30px;">
              <div class="card-block" style="background: rgba(0,0,0,0.6); width: 100%;display: inline-block;">
              <h1 class="card-title" style="color:white;font-weight: bolder;font-size: 44px;"><i class="glyphicon glyphicon-book"></i> What book do you want to read..</h1>
              <p class="card-text">
              <i style="font-size:100px; color: green;"></i>
              </p>
             </div>

              </div>

           </div>
           <div class="container">
             <div align="center" class="card card-inverse card-danger col-md-12 " style="width: 100%;padding: 30px;">
              <div class="card-block" style="background: rgba(255,234,0,0.6); width: 30%;display: inline-block;">
              <h1 class="card-title" style="color:white;"><a class="white" href="{{ url_for('admin.list_books') }}">Browse Books</a></h1>
              <p class="card-text">
              <i style="font-size:100px; color: green;"></i>
              </p>
             </div>



           </div>

            {{no_of_books}}
    </div>
</div>
{% endif    %}
{% endblock %}

app/templates/home/index.html
{% extends "base.html"%}

{% block title%}

Homepage
{% endblock title %}

{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                <ul>
                    <h1>Super Library</h1>
                    <h3>Know where your books are!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
                <div class="jumbotron" style="">
            <img src="{{ url_for('static', filename='img/case.jpg') }}" width="100%" style="position:absolute; left:0px; top:0px;  ">

            <div align="center" class="card card-inverse card-danger col-md-12 " style="width: 100%;padding: 30px;">
              <div class="card-block" style="background: rgba(0,0,0,0.6); width: 100%;display: inline-block;">
              <h1 class="card-title" style="color:white;font-weight: bolder;font-size: 44px;"><i class="glyphicon glyphicon-book"></i> Read the books you want to read..</h1>
              <p class="card-text">
              <i style="font-size:100px; color: aliceblue;" class="glyphicon glyphicon-star"></i>
              </p>
             </div>

              </div>
                      <div class="pull-right col-md-12" style="text-align: right; margin-top: 10%; margin-left: 60%">
                      <div class="lead col-md-3" >
                        <a class="btn btn-lg btn-success btn-lg" href="{{url_for('auth.login')}}" role="button">Admin</a>
                      </div>
                        <div class="lead col-md-3">
                        <a class="btn btn-lg btn-default btn-lg" href="{{url_for('auth.login')}}" role="button">User</a>
                      </div>
                      </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body%}